package fs

import (
	"github.com/malivvan/yuki/goja"
)

func (m *fsModule) defineConstants(obj *goja.Object) {
	c := m.r.NewObject()
	def := func(key string, val any) {
		_ = c.DefineDataProperty(key, m.r.ToValue(val), goja.FLAG_FALSE, goja.FLAG_FALSE, goja.FLAG_TRUE)
	}
	def("UV_FS_SYMLINK_DIR", 1)
	def("UV_FS_SYMLINK_JUNCTION", 2)
	def("O_RDONLY", 0)
	def("O_WRONLY", 1)
	def("O_RDWR", 2)
	def("UV_DIRENT_UNKNOWN", 0)
	def("UV_DIRENT_FILE", 1)
	def("UV_DIRENT_DIR", 2)
	def("UV_DIRENT_LINK", 3)
	def("UV_DIRENT_FIFO", 4)
	def("UV_DIRENT_SOCKET", 5)
	def("UV_DIRENT_CHAR", 6)
	def("UV_DIRENT_BLOCK", 7)
	def("S_IFMT", 61440)
	def("S_IFREG", 32768)
	def("S_IFDIR", 16384)
	def("S_IFCHR", 8192)
	def("S_IFBLK", 24576)
	def("S_IFIFO", 4096)
	def("S_IFLNK", 40960)
	def("S_IFSOCK", 49152)
	def("O_CREAT", 64)
	def("O_EXCL", 128)
	def("UV_FS_O_FILEMAP", 0)
	def("O_NOCTTY", 256)
	def("O_TRUNC", 512)
	def("O_APPEND", 1024)
	def("O_DIRECTORY", 65536)
	def("O_NOATIME", 262144)
	def("O_NOFOLLOW", 131072)
	def("O_SYNC", 1052672)
	def("O_DSYNC", 4096)
	def("O_DIRECT", 16384)
	def("O_NONBLOCK", 2048)
	def("S_IRWXU", 448)
	def("S_IRUSR", 256)
	def("S_IWUSR", 128)
	def("S_IXUSR", 64)
	def("S_IRWXG", 56)
	def("S_IRGRP", 32)
	def("S_IWGRP", 16)
	def("S_IXGRP", 8)
	def("S_IRWXO", 7)
	def("S_IROTH", 4)
	def("S_IWOTH", 2)
	def("S_IXOTH", 1)
	def("F_OK", 0)
	def("R_OK", 4)
	def("W_OK", 2)
	def("X_OK", 1)
	def("UV_FS_COPYFILE_EXCL", 1)
	def("COPYFILE_EXCL", 1)
	def("UV_FS_COPYFILE_FICLONE", 2)
	def("COPYFILE_FICLONE", 2)
	def("UV_FS_COPYFILE_FICLONE_FORCE", 4)
	def("COPYFILE_FICLONE_FORCE", 4)

	_ = obj.Set("constants", c)
	def = func(key string, val any) {
		_ = obj.DefineDataProperty(key, m.r.ToValue(val), goja.FLAG_FALSE, goja.FLAG_FALSE, goja.FLAG_TRUE)
	}
	def("F_OK", 0)
	def("R_OK", 4)
	def("W_OK", 2)
	def("X_OK", 1)
}
